name: Gradle Package

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle :clean :build api:clean api:build bukkit:clean bukkit:build bukkit:shadowJar

    - name: Upload build artifacts api
      uses: actions/upload-artifact@v1
      with:
        name: packetevents-api-dev-build.jar
        path: api/build/libs
        
    - name: Upload build artifacts bukkit
      uses: actions/upload-artifact@v1
      with:
        name: packetevents-bukkit-dev-build.jar
        path: bukkit/build/libs
